### ISSUE TITLE
Forwarding is under-specified

### ISSUE THREAD

**Issue by martinthomson** [DavidSchinazi/draft-cms-masque-connect-ip#10]
When an IP packet arrives, how is it forwarded?  What if the packet comes from a source outside of the declared routes?

When a DATAGRAM or IP_PACKET chunk arrives, how is that forwarded?  What if the packet contains a source address that is not assigned?  What if the packet contains a destination address that is not within a declared route?

Does the forwarding entity touch the TTL?  That is, is it a router?  I'm guessing that it does not touch the TTL on the basis that this is effectively a protocol for remote access to an IP interface, but it's probably worth getting that down.

What other modifications might be permitted?  Would it be reasonable to bleach DSCP or ECN or is that bad mojo?  It's probably not necessary to stipulate this as a matter of conformance, as any entity that carries IP might have their own policies regarding what they might want to do to packets, but it might be sensible to establish expectations, namely that IP packets are expected to be conveyed as received without modification assuming that the source and destination addresses are accurate.

**Comment by DavidSchinazi** [comment]
This sounds like a matter of local policy more than protocol design. If we look at the [Inbound Packet Processing section of the IPsec ESP RFC](https://datatracker.ietf.org/doc/html/rfc4303#section-3.4), it doesn't comment on what policy the decapsulating node uses.

**Comment by achernya** [comment]
I would prefer that we not have to comment on these topics for CONNECT-IP. In our existing implementation in QBONE, the answer to these questions is as follows:

1. Packets are forwarded by way of raw sockets if they match an assigned source address range and are targeting a destination address in the ranges specified by the route messages. If a packet cannot be forwarded/transmitted we will send back the appropriate ICMP error code.
2. QBONE does not decrement the TTL.
3. QBONE does not rewrite DSCP today but I think that should be explicitly permitted. Different networks use DSCP codepoints differently.
4. Rewriting ECN sounds like a bad idea, if we were to delve into policy I think we should make that a SHOULD/MUST NOT.

**Comment by martinthomson** [comment]
That others have neglected to specify critical functions is no excuse for making the same error.  What QBONE does (1 and 2) is entirely reasonable - and would establish the appropriate expectations.  I would be happy to avoid discussion of packet modifications.

**Comment by achernya** [comment]
Martin, do you feel this discussion belongs in this implementation document, or do you think it could/should perhaps be broken out as a separate set of recommendations? I worry about delving too far into policy because while these choices may be reasonable for the use cases we have envisioned today, I would like to avoid unnecessarily constraining things down the line. I suppose we could specify them and and revise them later if need be.

**Comment by martinthomson** [comment]
I think that you need some MUST-level requirements or you don't have a protocol.

**Comment by DavidSchinazi** [comment]
@martinthomson do you have some suggestions for some MUST-level requirements? I'm not sure if you have policy in mind or mechanics, and some examples might help.

**Comment by martinthomson** [comment]
There are three things you need MUSTs for:

1. IP packets received by the proxy.
2. IP_PACKET chunks received by the proxy.
3. DATAGRAM frames received by the proxy.

In all cases, it would be if $CASE, construct $THING and forward with $DETAILS.

**Comment by DavidSchinazi** [comment]
Fixed by #17
