### ISSUE TITLE
Better document how HTTP/3 Datagrams are used

### ISSUE THREAD

**Issue by gloinul** [DavidSchinazi/draft-cms-masque-connect-ip#4]
I am missing the definition of the usage of the HTTP/3 datagram flow-ID and how to establish that for a particular Connect-IP request. Although this likely are very similar to Connect-UDP it still needs to be defined. Although a single flow-IP per direction is likely sufficient for now as ECN, ICMP etc will be forward as part of the payload packets to the peer endpoint. 

From my perspective we clearly need capability that supports multiple parallel Connect-X requests over the same QUIC HTTP/3 connection.

**Comment by DavidSchinazi** [comment]
@gloinul you're absolutely correct. We've intentionally left this vague for now until we get resolutions on the ongoing conversations around draft-ietf-masque-h3-datagram. We'll update draft-cms-masque-connect-ip once we've made those decisions in draft-ietf-masque-h3-datagram.
