### ISSUE TITLE
Chunk type extensibility is under-specified

### ISSUE THREAD

**Issue by martinthomson** [DavidSchinazi/draft-cms-masque-connect-ip#9]
I'm assuming that the model here is "MUST-ignore unknown", but it doesn't really say that.  It probably needs a little more language about how a design might be able to decide that a peer supports a feature, such that it can continue to use the extension without fear of wasting bandwidth.

**Comment by DavidSchinazi** [comment]
We already have this text in the Stream Chunks section:
>  Endpoints that receive a chunk with an unknown CONNECT-IP Stream Chunk Type MUST silently skip over that chunk.

But I agree that we can flesh out our Extensibility Considerations section.
